imports:
    - { resource: "services/form.yml" }

services:
    _defaults:
        public: true

    coreshop.collector.taxes:
        class: CoreShop\Component\Taxation\Collector\TaxCollector
        arguments:
            - '@coreshop.repository.tax_rate'
            - '@coreshop.factory.tax_item'